### ISSUE TITLE
Error C2664 in HTTPRequest.hpp file

### ISSUE THREAD

**Issue by b-a-n-f** [elnormous/HTTPRequest#11]
Within file HTTPRequest.hpp, line 379, we get error C2664.
Changing the line to `std::unique_ptr<addrinfo, void(__stdcall*)(addrinfo*)> addressInfo(info, freeaddrinfo);` seems to fix the issue.

**Comment by elnormous** [comment]
Fixed in https://github.com/elnormous/HTTPRequest/commit/6b622601cb370a9fc0ab13d1ab5644a6902ddf94
