### ISSUE TITLE
Errors when trying to build a DLL

### ISSUE THREAD

**Issue by DualByte** [elnormous/HTTPRequest#13]
I get these errors`Severity	Code	Description	Project	File	Line	Suppression State
Error	C2011	 'sockproto': 'struct' type redefinition	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\WinSock2.h	462	
Error	C2375	 'accept': redefinition; different linkage	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\WinSock2.h	1625	
Error	C2375	 'bind': redefinition; different linkage	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\WinSock2.h	1647	
Error	C2375	 'closesocket': redefinition; different linkage	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\WinSock2.h	1668	
Error	C2375	 'connect': redefinition; different linkage	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\WinSock2.h	1685	
Error	C2011	 'fd_set': 'struct' type redefinition	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\WinSock2.h	136	
Error	C2065	 'Filter': undeclared identifier	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\ws2tcpip.h	740	
Error	C2065	 'Filter': undeclared identifier	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\ws2tcpip.h	743	
Error	C2065	 'Filter': undeclared identifier	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\ws2tcpip.h	749	
Error	C2065	 'Filter': undeclared identifier	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\ws2tcpip.h	750	
Error	C2065	 'Filter': undeclared identifier	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\ws2tcpip.h	755	
Error	C2065	 'Filter': undeclared identifier	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\ws2tcpip.h	756	
Error	C2065	 'Filter': undeclared identifier	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\ws2tcpip.h	757	
Error	C2065	 'Filter': undeclared identifier	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\ws2tcpip.h	758	
Error	C2065	 'Filter': undeclared identifier	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\ws2tcpip.h	760	
Error	C2065	 'Filter': undeclared identifier	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\ws2tcpip.h	764	
Error	C2065	 'Filter': undeclared identifier	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\ws2tcpip.h	767	
Error	C2065	 'Filter': undeclared identifier	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\ws2tcpip.h	786	
Error	C2065	 'Filter': undeclared identifier	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\ws2tcpip.h	789	
Error	C2065	 'FilterMode': undeclared identifier	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\ws2tcpip.h	757	
Error	C2375	 'gethostbyaddr': redefinition; different linkage	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\WinSock2.h	2197	
Error	C2375	 'gethostbyname': redefinition; different linkage	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\WinSock2.h	2219	
Error	C2375	 'gethostname': redefinition; different linkage	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\WinSock2.h	2236	
Error	C2375	 'getpeername': redefinition; different linkage	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\WinSock2.h	1729	
Error	C2375	 'getprotobyname': redefinition; different linkage	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\WinSock2.h	2331	
Error	C2375	 'getprotobynumber': redefinition; different linkage	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\WinSock2.h	2314	
Error	C2375	 'getservbyname': redefinition; different linkage	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\WinSock2.h	2295	
Error	C2375	 'getservbyport': redefinition; different linkage	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\WinSock2.h	2276	
Error	C2375	 'getsockname': redefinition; different linkage	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\WinSock2.h	1750	
Error	C2375	 'getsockopt': redefinition; different linkage	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\WinSock2.h	1771	
Error	C2011	 'hostent': 'struct' type redefinition	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\WinSock2.h	236	
Error	C2375	 'htonl': redefinition; different linkage	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\WinSock2.h	1796	
Error	C2375	 'htons': redefinition; different linkage	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\WinSock2.h	1813	
Error	C2375	 'inet_addr': redefinition; different linkage	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\WinSock2.h	1831	
Error	C2375	 'inet_ntoa': redefinition; different linkage	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\WinSock2.h	1849	
Error	C2375	 'ioctlsocket': redefinition; different linkage	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\WinSock2.h	1706	
Error	C2065	 'IP_MSFILTER': undeclared identifier	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\ws2tcpip.h	748	
Error	C2065	 'IP_MSFILTER': undeclared identifier	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\ws2tcpip.h	794	
Error	C2011	 'linger': 'struct' type redefinition	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\WinSock2.h	504	
Error	C2375	 'listen': redefinition; different linkage	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\WinSock2.h	1949	
Error	C2660	 'memcpy': function does not take 2 arguments	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\ws2tcpip.h	760	
Error	C2011	 'netent': 'struct' type redefinition	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\WinSock2.h	249	
Error	C2375	 'ntohl': redefinition; different linkage	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\WinSock2.h	1968	
Error	C2375	 'ntohs': redefinition; different linkage	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\WinSock2.h	1985	
Error	C2065	 'PIP_MSFILTER': undeclared identifier	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\ws2tcpip.h	740	
Error	C2065	 'PIP_MSFILTER': undeclared identifier	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\ws2tcpip.h	749	
Error	C2065	 'PIP_MSFILTER': undeclared identifier	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\ws2tcpip.h	786	
Error	C2011	 'protoent': 'struct' type redefinition	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\WinSock2.h	268	
Error	C2375	 'recv': redefinition; different linkage	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\WinSock2.h	2002	
Error	C2375	 'recvfrom': redefinition; different linkage	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\WinSock2.h	2025	
Error	C2375	 'select': redefinition; different linkage	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\WinSock2.h	2052	
Error	C2375	 'send': redefinition; different linkage	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\WinSock2.h	2077	
Error	C2375	 'sendto': redefinition; different linkage	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\WinSock2.h	2100	
Error	C2011	 'servent': 'struct' type redefinition	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\WinSock2.h	256	
Error	C2375	 'setsockopt': redefinition; different linkage	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\WinSock2.h	2127	
Error	C2375	 'shutdown': redefinition; different linkage	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\WinSock2.h	2152	
Error	C2011	 'sockaddr': 'struct' type redefinition	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\shared\ws2def.h	238	
Error	C2011	 'sockaddr_in': 'struct' type redefinition	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\shared\ws2def.h	636	
Error	C2375	 'socket': redefinition; different linkage	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\WinSock2.h	2172	
Error	C2065	 'SourceCount': undeclared identifier	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\ws2tcpip.h	742	
Error	C2065	 'SourceCount': undeclared identifier	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\ws2tcpip.h	748	
Error	C2065	 'SourceCount': undeclared identifier	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\ws2tcpip.h	758	
Error	C2065	 'SourceCount': undeclared identifier	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\ws2tcpip.h	759	
Error	C2065	 'SourceCount': undeclared identifier	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\ws2tcpip.h	760	
Error	C2065	 'SourceCount': undeclared identifier	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\ws2tcpip.h	788	
Error	C2065	 'SourceList': undeclared identifier	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\ws2tcpip.h	743	
Error	C2065	 'SourceList': undeclared identifier	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\ws2tcpip.h	760	
Error	C2065	 'SourceList': undeclared identifier	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\ws2tcpip.h	789	
Error	C2011	 'timeval': 'struct' type redefinition	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\WinSock2.h	180	
Error	C2375	 'WSAAsyncGetHostByAddr': redefinition; different linkage	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\WinSock2.h	2632	
Error	C2375	 'WSAAsyncGetHostByName': redefinition; different linkage	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\WinSock2.h	2606	
Error	C2375	 'WSAAsyncGetProtoByName': redefinition; different linkage	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\WinSock2.h	2554	
Error	C2375	 'WSAAsyncGetProtoByNumber': redefinition; different linkage	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\WinSock2.h	2580	
Error	C2375	 'WSAAsyncGetServByName': redefinition; different linkage	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\WinSock2.h	2498	
Error	C2375	 'WSAAsyncGetServByPort': redefinition; different linkage	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\WinSock2.h	2526	
Error	C2375	 'WSAAsyncSelect': redefinition; different linkage	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\WinSock2.h	2680	
Error	C2375	 'WSACancelAsyncRequest': redefinition; different linkage	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\WinSock2.h	2662	
Error	C2375	 'WSACancelBlockingCall': redefinition; different linkage	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\WinSock2.h	2480	
Error	C2375	 'WSACleanup': redefinition; different linkage	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\WinSock2.h	2371	
Error	C2011	 'WSAData': 'struct' type redefinition	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\WinSock2.h	364	
Error	C2375	 'WSAGetLastError': redefinition; different linkage	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\WinSock2.h	2405	
Error	C2375	 'WSAIsBlocking': redefinition; different linkage	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\WinSock2.h	2426	
Error	C2375	 'WSASetBlockingHook': redefinition; different linkage	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\WinSock2.h	2462	
Error	C2375	 'WSASetLastError': redefinition; different linkage	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\WinSock2.h	2388	
Error	C2065	 'WSASetLastError': undeclared identifier	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\ws2tcpip.h	744	
Error	C2065	 'WSASetLastError': undeclared identifier	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\ws2tcpip.h	751	
Error	C2065	 'WSASetLastError': undeclared identifier	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\ws2tcpip.h	790	
Error	C2375	 'WSAStartup': redefinition; different linkage	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\WinSock2.h	2351	
Error	C2375	 'WSAUnhookBlockingHook': redefinition; different linkage	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\WinSock2.h	2444	
Error	C2447	 '{': missing function header (old-style formal list?)	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\shared\ws2ipdef.h	42	
Error	C1003	 error count exceeds 100; stopping compilation	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\ws2tcpip.h	794	
Error	C4430	 missing type specifier - int assumed. Note: C++ does not support default-int	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\shared\ws2def.h	494	
Error	C4430	 missing type specifier - int assumed. Note: C++ does not support default-int	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\shared\ws2def.h	494	
Error	C2059	 syntax error: 'constant'	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\shared\ws2def.h	440	
Error	C2059	 syntax error: '}'	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\WinSock2.h	4206	
Error	C2061	 syntax error: identifier 'MULTICAST_MODE_TYPE'	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\ws2tcpip.h	733	
Error	C2061	 syntax error: identifier 'MULTICAST_MODE_TYPE'	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\ws2tcpip.h	779	
Error	C2143	 syntax error: missing ';' before '{'	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\shared\ws2ipdef.h	42	
Error	C2143	 syntax error: missing ';' before '}'	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\shared\ws2def.h	494	
Error	C2143	 syntax error: missing ';' before '}'	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\WinSock2.h	4206	
Error	C2146	 syntax error: missing ';' before identifier 'Filter'	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\ws2tcpip.h	740	
Error	C2146	 syntax error: missing ';' before identifier 'Filter'	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\ws2tcpip.h	786	
Error	C2146	 syntax error: missing ';' before identifier 'HeapAlloc'	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\ws2tcpip.h	749	
Error	C2143	 syntax error: missing '}' before 'constant'	DeltaWare	C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\shared\ws2def.h	440	
`

**Comment by elnormous** [comment]
What version of Visual Studio are you using?

**Comment by herbertdai** [comment]
Visual studio 2019

Elviss Strazdins <notifications@github.com>于2019年11月9日 周六上午7:00写道：

**Comment by elnormous** [comment]
I just tested the test app and it compiled with Visual Studio 2019. Can you please confirm that you can build the test app?

**Comment by elnormous** [comment]
Ok, I think I reproduced your problem. I included <Windows.h> before HTTPRequest.hpp and got a similar error.
Is it possible for you to not include Windows.h before HTTPRequest.hpp?
See this for a description of the problem: https://stackoverflow.com/questions/21399650/cannot-include-both-files-winsock2-windows-h
