### ISSUE TITLE
Receive the following errors when trying to include 

### ISSUE THREAD

**Issue by bmkern02** [elnormous/HTTPRequest#19]
HTTPRequest.hpp: In member function 'http::Response http::Request::send(const string&, const string&, const std::vector<std::__cxx11::basic_string<char> >&)':
HTTPRequest.hpp:398:72: error: 'getaddrinfo' was not declared in this scope
             if (getaddrinfo(domain.c_str(), port.c_str(), &hints, &info) != 0)
                                                                        ^
HTTPRequest.hpp:401:49: error: 'freeaddrinfo' was not declared in this scope
             std::unique_ptr<addrinfo, decltype(&freeaddrinfo)> addressInfo(info, freeaddrinfo);
                                                 ^~~~~~~~~~~~
HTTPRequest.hpp:401:62: error: template argument 2 is invalid
             std::unique_ptr<addrinfo, decltype(&freeaddrinfo)> addressInfo(info, freeaddrinfo);
                                                              ^
HTTPRequest.hpp:401:94: error: expression list treated as compound expression in initializer [-fpermissive]
             std::unique_ptr<addrinfo, decltype(&freeaddrinfo)> addressInfo(info, freeaddrinfo);
                                                                                              ^
HTTPRequest.hpp:406:46: error: base operand of '->' is not a pointer
             if (::connect(socket, addressInfo->ai_addr, static_cast<socklen_t>(addressInfo->ai_addrlen)) < 0)
                                              ^~
HTTPRequest.hpp:406:91: error: base operand of '->' is not a pointer
             if (::connect(socket, addressInfo->ai_addr, static_cast<socklen_t>(addressInfo->ai_addrlen)) < 0)

**Comment by quantumcore** [comment]
Same error over here.
```bash

HTTPRequest.hpp: In member function 'http::Response http::Request::send(const string&, const string&, const std::vector<std::__cxx11::basic_string<char> >&)':
HTTPRequest.hpp:398:72: error: 'getaddrinfo' was not declared in this scope    
             if (getaddrinfo(domain.c_str(), port.c_str(), &hints, &info) != 0)
                                                                        ^
HTTPRequest.hpp:401:49: error: 'freeaddrinfo' was not declared in this scope
             std::unique_ptr<addrinfo, decltype(&freeaddrinfo)> addressInfo(info, freeaddrinfo);
                                                 ^~~~~~~~~~~~
HTTPRequest.hpp:401:62: error: template argument 2 is invalid
             std::unique_ptr<addrinfo, decltype(&freeaddrinfo)> addressInfo(info, freeaddrinfo);
                                                              ^
HTTPRequest.hpp:401:94: error: expression list treated as compound expression in initializer [-fpermissive]
             std::unique_ptr<addrinfo, decltype(&freeaddrinfo)> addressInfo(info, freeaddrinfo);
                                                                                              ^
HTTPRequest.hpp:406:46: error: base operand of '->' is not a pointer
             if (::connect(socket, addressInfo->ai_addr, static_cast<socklen_t>(addressInfo->ai_addrlen)) < 0)
                                              ^~
HTTPRequest.hpp:406:91: error: base operand of '->' is not a pointer
             if (::connect(socket, addressInfo->ai_addr, static_cast<socklen_t>(addressInfo->ai_addrlen)) < 0)
                                                                                           ^~
```

**Comment by elnormous** [comment]
What compiler/OS/WindowsSDK/C++ version you use?

**Comment by quantumcore** [comment]
@elnormous I'm using GCC, C++11.

**Comment by elnormous** [comment]
I can not reproduce this with any version of gcc. What version of gcc are you using? What operating system?

**Comment by quantumcore** [comment]
GCC Version is gcc version 6.3.0, Operating System Windows.
Compiled : ``g++ main.cpp``

**Comment by elnormous** [comment]
Are you using cygwin on mingw?

**Comment by elnormous** [comment]
Ok, this is a problem with MinGW. Fixed it in https://github.com/elnormous/HTTPRequest/commit/14b3beb633f879253e063452dd4fe723d59e1210
