### ISSUE TITLE
argument of type "uint8_t *" is incompatible with parameter of type "const char *" HTTPRequest.hpp line 454

### ISSUE THREAD

**Issue by ammaresit** [elnormous/HTTPRequest#20]
Hello, first i would like to thank you for producing such useful thing. However i have a problem as detailed below. Thanks in advance.

Line 454:
const auto size = ::send(socket, requestData.data() + sent, static_cast<size_t>(remaining), flags);

second parameter of ::send() [requestData.data()] is the problem according to Visual Studio 2019 (version 16.4.4) on Windows10. Any suggestions?

**Comment by elnormous** [comment]
Fixed in https://github.com/elnormous/HTTPRequest/commit/445e67e6deb0909bedb0fdf6c5c23fad4a64014c
