### ISSUE TITLE
It needs to be handled in this way, otherwise an error will be reported

### ISSUE THREAD

**Issue by Knove** [elnormous/HTTPRequest#26]
It needs to be handled in this way, otherwise an error will be reported:

![image](https://user-images.githubusercontent.com/27696426/104011505-2a123c00-51e9-11eb-91dc-1835d95137a7.png)

VS 2019

**Comment by elnormous** [comment]
Please explain why?

**Comment by Knove** [comment]
![image](https://user-images.githubusercontent.com/27696426/104092142-fef91c80-52bc-11eb-87aa-7c48ec6bd088.png)
 can try this on 
![image](https://user-images.githubusercontent.com/27696426/104092171-22bc6280-52bd-11eb-951d-24b4013b9012.png)

**Comment by elnormous** [comment]
This is because you are including Windows.h before HTTPRequest.hpp without defining WIN32_LEAN_AND_MEAN first.

**Comment by elnormous** [comment]
Ok, added parentheses in https://github.com/elnormous/HTTPRequest/commit/bc1301f731306276af47ad9f78081a0fd504520c
