### ISSUE TITLE
Is there a plan to IPV6 Support

### ISSUE THREAD

**Issue by darkspiderbots** [elnormous/HTTPRequest#3]
Dear, nice Source did you plane to support ipv6 also?

**Comment by elnormous** [comment]
Yes, I probably will do that.

**Comment by HenkieHanker2** [comment]
> Yes, I probably will do that.

Would be awsome, i'm struggling with the same problem.

**Comment by elnormous** [comment]
I implemented IPv6 support in https://github.com/elnormous/HTTPRequest/commit/ee5f3863f2a734f924d62b81aedd1bdd86f23e55
