### ISSUE TITLE
Identfier AI_DEFAULT is undefined

### ISSUE THREAD

**Issue by 552bb224b12ac67f3a9f94276e491563** [elnormous/HTTPRequest#4]
Whenever I run my program I get this error 

addrinfo hints;
hints.ai_flags = AI_DEFAULT;

line 315

please help

**Comment by elnormous** [comment]
This is fixed in https://github.com/elnormous/HTTPRequest/commit/88453fe5277cd3b3932ac927ca3567fde2ae862a
