### ISSUE TITLE
Linking error

### ISSUE THREAD

**Issue by zsoltardai** [elnormous/HTTPRequest#43]
Hey, I'm kinda new to C++, and I've been trying to include your .hpp file in my project and it gave me these linking errors:
I've included the file in the project and the IDE recognizes it, but It gives these linking errors when I try to build it.
Do you have any tips to fix this issue?
![snippet](https://user-images.githubusercontent.com/61164189/123273237-c2377f80-d502-11eb-904e-bd47d51c1824.png)

**Comment by 805436085** [comment]
`#pragma comment(lib, "Ws2_32.lib")`

**Comment by elnormous** [comment]
Yes, you have to link ws2_32.lib to your executable.

**Comment by zsoltardai** [comment]
Thank you so much! It works! 😀😀
