### ISSUE TITLE
Need to specify port in request header!

### ISSUE THREAD

**Issue by Zhang-Muyang** [elnormous/HTTPRequest#46]
When I used the method "POST" and an address with port number 8080. I always got an 502 bad gateway error. After using wireshark and compare the c++ post request with the curl post request, I found that in the header you need to concatenate the port number after the domain! In the original implementation, the header string just contains a domain there.

I am not a native speaker, and any discussion is welcomed. I'll start a pull request later time.

**Comment by elnormous** [comment]
This is fixed in https://github.com/elnormous/HTTPRequest/commit/cdaa3cd589205a1bc6f1057492aab42b14d2ebd5
