### ISSUE TITLE
Message headers are case-insensitive

### ISSUE THREAD

**Issue by tysenmoore-xse** [elnormous/HTTPRequest#48]
According to RFC 2616 the [Message Headers](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2) are case-insensitive (stated as: "Field names are case-insensitive").  However, your code is checking for "Content-Length" and "Transfer-Encoding" in a case sensitive manner so it does not process the response for some web servers.  Any chance this can be modified?  If a PR is better I can provide one.

**Comment by elnormous** [comment]
Thank you! Fixed in https://github.com/elnormous/HTTPRequest/commit/e2863f8cb331bdd89534dda8b4af2d30e9f2e033.
