### ISSUE TITLE
How about CI / CD?

### ISSUE THREAD

**Issue by DBJDBJ** [elnormous/HTTPRequest#51]
https://github.blog/2022-02-02-build-ci-cd-pipeline-github-actions-four-steps/

**Comment by elnormous** [comment]
I first have to write tests to run something on CI. Had a plan to do it for a long time. I guess this is the time to finally do it.

**Comment by DBJDBJ** [comment]
https://github.com/sheredom/utest.h

**Comment by elnormous** [comment]
I remembered that I am actually running the build on Azure Pipelines: https://github.com/elnormous/HTTPRequest/blob/master/azure-pipelines.yml
I added jobs for unit tests to it.
