### ISSUE TITLE
Does it support C++11?

### ISSUE THREAD

**Issue by b1ek** [elnormous/HTTPRequest#54]
I got a bunch of errors trying to compile it. test/Makefile says its c++17. Just to make sure, does it support 11 or am i missing something??

If it doesn't, you should write supported versions in README

**Comment by elnormous** [comment]
No it does not. I added C++17 to README in https://github.com/elnormous/HTTPRequest/commit/01e4b7838185d7623ea228d83493f7143e79ae20.
