### ISSUE TITLE
HTTPS support?

### ISSUE THREAD

**Issue by samuelclay** [elnormous/HTTPRequest#7]
This is a great compact library but I would need HTTPS support in order to use it. Is this a possibility?

**Comment by samuelclay** [comment]
Aww nuts, just noticed #2. But still, is there a guide for adding https support?

**Comment by elnormous** [comment]
Here is an HTTPS (also known as [HTTP](https://tools.ietf.org/html/rfc2818) over [TLS](https://tools.ietf.org/html/rfc5246)) client sample on [openssl.org](https://wiki.openssl.org/index.php/SSL/TLS_Client). You should be able to get the idea from it. Also, check out source code of other projects that can make https requests (like curl).
