### ISSUE TITLE
On windows i get some random errors?

### ISSUE THREAD

**Issue by DualByte** [elnormous/HTTPRequest#8]
I just imported this into my project and i get these errors
`Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol __imp_connect referenced in function "public: struct http::Response __cdecl http::Request::send(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::vector<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::allocator<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > const &)" (?send@Request@http@@QEAA?AUResponse@2@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0AEBV?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@5@@Z)	C:\Users\d0b\source\repos\NGDDoS\CMakeLists.txt	C:\Users\d0b\source\repos\NGDDoS\NGDDoS.cpp.obj	1	
Error	LNK2019	unresolved external symbol __imp_closesocket referenced in function "private: void __cdecl http::Socket::close(void)" (?close@Socket@http@@AEAAXXZ)	C:\Users\d0b\source\repos\NGDDoS\CMakeLists.txt	C:\Users\d0b\source\repos\NGDDoS\NGDDoS.cpp.obj	1	
Error	LNK2019	unresolved external symbol __imp_recv referenced in function "public: struct http::Response __cdecl http::Request::send(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::vector<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::allocator<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > const &)" (?send@Request@http@@QEAA?AUResponse@2@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0AEBV?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@5@@Z)	C:\Users\d0b\source\repos\NGDDoS\CMakeLists.txt	C:\Users\d0b\source\repos\NGDDoS\NGDDoS.cpp.obj	1	
Error	LNK2019	unresolved external symbol __imp_send referenced in function "public: struct http::Response __cdecl http::Request::send(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::vector<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::allocator<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > const &)" (?send@Request@http@@QEAA?AUResponse@2@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0AEBV?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@5@@Z)	C:\Users\d0b\source\repos\NGDDoS\CMakeLists.txt	C:\Users\d0b\source\repos\NGDDoS\NGDDoS.cpp.obj	1	
Error	LNK2019	unresolved external symbol __imp_socket referenced in function "public: __cdecl http::Socket::Socket(enum http::InternetProtocol)" (??0Socket@http@@QEAA@W4InternetProtocol@1@@Z)	C:\Users\d0b\source\repos\NGDDoS\CMakeLists.txt	C:\Users\d0b\source\repos\NGDDoS\NGDDoS.cpp.obj	1	
Error	LNK2019	unresolved external symbol __imp_WSAStartup referenced in function "public: __cdecl http::WinSock::WinSock(void)" (??0WinSock@http@@QEAA@XZ)	C:\Users\d0b\source\repos\NGDDoS\CMakeLists.txt	C:\Users\d0b\source\repos\NGDDoS\NGDDoS.cpp.obj	1	
Error	LNK2019	unresolved external symbol __imp_WSACleanup referenced in function "public: __cdecl http::WinSock::~WinSock(void)" (??1WinSock@http@@QEAA@XZ)	C:\Users\d0b\source\repos\NGDDoS\CMakeLists.txt	C:\Users\d0b\source\repos\NGDDoS\NGDDoS.cpp.obj	1	
Error	LNK2019	unresolved external symbol __imp_WSAGetLastError referenced in function "int __cdecl http::getLastError(void)" (?getLastError@http@@YAHXZ)	C:\Users\d0b\source\repos\NGDDoS\CMakeLists.txt	C:\Users\d0b\source\repos\NGDDoS\NGDDoS.cpp.obj	1	
Error	LNK2019	unresolved external symbol __imp_getaddrinfo referenced in function "public: struct http::Response __cdecl http::Request::send(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::vector<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::allocator<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > const &)" (?send@Request@http@@QEAA?AUResponse@2@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0AEBV?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@5@@Z)	C:\Users\d0b\source\repos\NGDDoS\CMakeLists.txt	C:\Users\d0b\source\repos\NGDDoS\NGDDoS.cpp.obj	1	
Error	LNK2019	unresolved external symbol __imp_freeaddrinfo referenced in function "public: struct http::Response __cdecl http::Request::send(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::vector<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::allocator<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > const &)" (?send@Request@http@@QEAA?AUResponse@2@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0AEBV?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@5@@Z)	C:\Users\d0b\source\repos\NGDDoS\CMakeLists.txt	C:\Users\d0b\source\repos\NGDDoS\NGDDoS.cpp.obj	1	
Error	LNK1120	10 unresolved externals	C:\Users\d0b\source\repos\NGDDoS\CMakeLists.txt	C:\Users\d0b\source\repos\NGDDoS\NGDDoS\NGDDoS.exe	1	
`

**Comment by elnormous** [comment]
You have to link ws2_32.lib to your executable. Please see the [Visual Studio documentation](https://docs.microsoft.com/en-us/cpp/build/reference/dot-lib-files-as-linker-input?view=vs-2019).
