### ISSUE TITLE
Implement support for timeout specification

### ISSUE THREAD

**Issue by mbitsnbites** [elnormous/HTTPRequest#9]
For the application I'm working on it would be useful to be able to specify the connection and send/recv timeout.

This could be implemented as an extra optional argument to relevant methods (e.g. `Request::send()`), as a connection-wide option to the `Request()` constructor, or something else.

**Comment by elnormous** [comment]
Yes, I had a plan to do that. This will be the next improvement I will do for it.

**Comment by elnormous** [comment]
Implemented connect and read/write timeouts.
